import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import Navbar from "./components/navbar";
import Banner from "./components/banner";
import Header from "./components/header";
import Product_list from "./components/product_list";
import Levelup from "./components/levelup";
import Footer from "./components/footer";
import Logos from "./components/logo_clouds";
import Status from "./components/status";
import Marketing from "./components/marketing_section"; 
import Collection from "./components/collection";
import Simple_productivity from "./components/simple_productivity";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <Navbar />
        <Banner />
        <Logos />
        <Product_list />
        <Levelup />
        <Collection />
        <Simple_productivity />
        <Footer />
        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
        {children}
      </body>
    </html>
  );
}
